services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - postgres.env
    networks:
      - bluenest
    volumes:
      - ./data/postgres:/data/db
networks:
  bluenest: